# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: video-ai-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_: